[package]
name = "devcon-proto"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
prost.workspace = true
bytes.workspace = true

[build-dependencies]
prost-build.workspace = true
